In [9]:
inputs['astro']

'C:\\Users\\Nathan\\Desktop\\Astro Data'

In [3]:
# SET I/O
inputs = {'astro' : '\Users\Nathan\SkyDrive\Documents'}
outputs = {'astro' : '\Users\Nathan\SkyDrive\Documents'}

# LIBRARIES
import os
import time
import numpy as np
import matplotlib as matplotlib
import matplotlib.pyplot as plt 
import pandas as pd 
import matplotlib.dates as mdates
from matplotlib.dates import date2num, num2date
from matplotlib import ticker
from pandas import DataFrame, Series, ExcelWriter
from datetime import datetime
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.offsetbox import TextArea, DrawingArea, OffsetImage, \
     AnnotationBbox
from matplotlib.cbook import get_sample_data
from matplotlib.ticker import FuncFormatter
pd.options.mode.chained_assignment = None

# SCRIPT SUMMARY
print("\n\n\n######################################################\n")
if '__file__' in globals():
    print("CURRENT SCRIPT:\n" + str(os.path.realpath(__file__)) + "\n")
print("INPUT FOLDERS:")
for key in inputs:
    print(inputs[key])
print("\nOUTPUT FOLDERS:")
for key in outputs:
    print(outputs[key])
print("\n######################################################\n")

## NOTE: Input files must be named in the format: name + "-" + date("YYYY-MM-DD")
# FIND OPPORTUNITY DATA
cd = os.chdir(inputs['astro'])
inputfiles = sorted(os.listdir(cd))
source = max(inputfiles)
print("Data Source >>> " + str(source))

filename = 'Sunrise Sunset-2015.txt'
firstdata = 9

# Using the newer with construct to close the file automatically.
with open(filename) as f:
    data = f.readlines()

# cut off extra crap
ssdata = data[firstdata:]
ssdata = pd.DataFrame(ssdata, columns=['raw data'])

ssdata['day'] = 0
ssdata['next'] = 0
for i in range(0,len(ssdata)):
    temp = ssdata['raw data'][i].split(" ")
    ssdata['day'] = temp[0]
    ssdata['next'] = temp[1]


ssdata.head(1)

######################################################

INPUT FOLDERS:
C:\Users\Nathan\Desktop\Astro Data

OUTPUT FOLDERS:
C:\Users\Nathan\Desktop\Astro Data

######################################################

TypeError: coercing to Unicode: need string or buffer, NoneType found

In [53]:
ssdata

                                             raw data day next
0   01  1551 0036  1532 0115  1449 0156  1351 0237...  \n
1   02  1551 0037  1531 0116  1447 0157  1349 0238...  \n
2   03  1551 0038  1529 0118  1445 0158  1347 0240...  \n
3   04  1551 0039  1528 0119  1444 0200  1345 0241...  \n
4   05  1551 0040  1527 0121  1442 0201  1343 0242...  \n
5   06  1551 0041  1526 0122  1440 0202  1341 0244...  \n
6   07  1550 0042  1524 0124  1438 0204  1339 0245...  \n
7   08  1550 0043  1523 0125  1436 0205  1338 0246...  \n
8   09  1550 0044  1521 0127  1434 0207  1336 0248...  \n
9   10  1550 0045  1520 0128  1433 0208  1334 0249...  \n
10  11  1549 0046  1519 0130  1431 0209  1332 0250...  \n
11  12  1549 0048  1517 0131  1429 0211  1330 0251...  \n
12  13  1548 0049  1516 0133  1427 0212  1328 0253...  \n
13  14  1548 0050  1514 0134  1425 0213  1327 0254...  \n
14  15  1547 0051  1512 0136  1423 0215  1325 0255...  \n
15  16  1547 0053  1511 0137  1421 0216  1323 0257...  \n
16  17  1546 0054  1509 0138  1419 0217  1321 0258...  \n
17  18  1545 0055  1508 0140  1417 0219  1320 0259...  \n
18  19  1545 0057  1506 0141  1416 0220  1318 0301...  \n
19  20  1544 0058  1505 0143  1414 0221  1316 0302...  \n
20  21  1543 0059  1503 0144  1412 0223  1314 0303...  \n
21  22  1542 0101  1501 0146  1410 0224  1313 0304...  \n
22  23  1541 0102  1459 0147  1408 0225  1311 0306...  \n
23  24  1540 0103  1458 0149  1406 0227  1309 0307...  \n
24  25  1539 0105  1456 0150  1404 0228  1308 0308...  \n
25  26  1538 0106  1454 0151  1402 0229  1306 0310...  \n
26  27  1537 0108  1453 0153  1400 0231  1305 0311...  \n
27  28  1536 0109  1451 0154  1358 0232  1303 0312...  \n
28  29  1535 0111             1356 0233  1301 0314...  \n
29  30  1534 0112             1355 0235  1300 0315...  \n
30  31  1533 0114             1353 0236           ...  \n
31                                                 \n  \n
32                                       Back to form  \n